### ISSUE TITLE
Customise the grant gui

### ISSUE THREAD

**Issue by frede69** [Yochran/yoCore#21]
Hi! I know this isn't a problem but I am new here, and don't know other places to ask.

I was just wondering if it's possible to customise the grant gui.

for example: 
all ranks in page1 and all permissions in page2?
delete pages?
change the size of the gui?
etc

Regards:
Frede/julepynt ;)

**Comment by Yochran** [comment]
You can't change the size of the GUI because pagination is set up for a GUI with 3 rows, the top row being the top toolbar, the bottom row being the bottom toolbar, and the middle row being the ranks/permissions.

You'll notice however, the ranks do already come before the permissions. However, if you have more than 9 ranks, they will overflow to the second page.

**Comment by frede69** [comment]
Ok I understand.
I have more then 9 ranks, so it's hard to use grant gui.

But are you ever going to update it, or leave it like that?
nice to know :P

**Comment by Yochran** [comment]
No. This plugin is nearly discontinued.
